# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15uJE8dLrSjXngyHg4bvPudCX4kSI9QOD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('database.csv.zip')
df.head()

df.shape

df.info()

df.describe()

plt.subplots(figsize=(15, 5))

plt.subplot(1, 2, 1)
sb.distplot(df['Depth'])

plt.subplot(1, 2, 2)
sb.boxplot(df['Depth'])

plt.show()

plt.subplots(figsize=(15, 5))

plt.subplot(1, 2, 1)
sb.distplot(df['Magnitude'])

plt.subplot(1, 2, 2)
sb.boxplot(df['Magnitude'])

plt.show()

plt.figure(figsize=(10, 8))
sb.scatterplot(data=df,
			x='Latitude',
			y='Longitude',
			hue='Magnitude')
plt.show()

import plotly.express as px
import pandas as pd

fig = px.scatter_geo(df, lat='Latitude',
					lon='Longitude',
					color="Magnitude",
					fitbounds='locations',
					scope='asia')
fig.show()